version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerback
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
    networks:
      - app-network
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: Dockerfront
    container_name: angular
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongo_test
    restart: unless-stopped
    volumes:     
      - ./dbdata:/data/db
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
